### PR TITLE
add tags to tests

### PR DESCRIPTION
**Pull request by berit**

### CODE REVIEW

**Comment by berit** [comment]
@plocket What is the desired behavior here? Just tags for non-english tests? Do we want to change which tests run depending on the trigger?

**Comment by plocket** [comment]
One thing we're looking for is the ability to run language tests without running the default language as well.

**Review by plocket — COMMENTED** [review]
This is mostly looking good. ~Not sure quite how this happened, but this isn't ignoring reports. Maybe something went wrong further upstream. Worth discussing. [If I recall, we were using `*_report_*` to ignore, or that's what was intended at least.]~

My mistake, I think. The reporting shouldn't be an issue here. Probably my fault for forgetting to reinstall something.

**Review by plocket — APPROVED** [review]
From what I can keep straight currently, I tested and previous issues and looks excellent.
1. `npm run langs` is runs only the specified languages locally.
1. [Running the workflow on this branch on github manually](https://github.com/plocket/docassemble-MAEvictionDefense/runs/1676964971?check_suite_focus=true) with one language and the `@fast` tag runs only the test with that tag for both English and whatever other languages are specified.

If we missed something, it shouldn't cause errors and, we should be able to get it on the next go around.

**Pull request merged**
